version: 0.0
os: linux
files:
  - source: /index.html
    destination: /var/www/html/
    overwrite: true
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: ubuntu
    - location: scripts/start_server
      timeout: 300
      runas: ubuntu
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: ubuntu
  AfterInstall:
    - location: scripts/run_buildout
      runas: ubuntu
    - location: scripts/upgrade_odoo
      runas: ubuntu
